[tool.pytest.ini_options]
markers = [
    "integration: Integration tests",
    "git: Git service integration tests",
    "llm: LLM service integration tests",
    "mcp: MCP (Model Context Protocol) related tests",
    "function_calling: Function calling related tests",
    "streaming: Streaming functionality tests",
    "tools: Tool execution tests",
    "performance: Performance tests",
    "slow: Slow running tests",
    "github: Tests requiring GitHub API access",
    "forgejo: Tests requiring Forgejo API access", 
    "openai: Tests requiring OpenAI API access",
    "unit: Unit tests",
    "e2e: End-to-end tests",
    "api: API tests"
]

testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-ra -q --tb=short"
asyncio_mode = "auto"

filterwarnings = [
    "ignore::DeprecationWarning:pytest.*",
    "ignore::DeprecationWarning:pydantic.*"
]

# Note: Legacy tests in tests/unit/services/llm/legacy/ are automatically skipped
# To run only active tests: pytest tests/unit/services/llm/ --ignore=tests/unit/services/llm/legacy/
