"""rename document_base_directory to document_root_directory and add root_document_path

Revision ID: a19110497896
Revises: fbb97998d2ce
Create Date: 2025-08-05 22:36:48.632511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a19110497896'
down_revision: Union[str, None] = 'fbb97998d2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('repository_root', sa.String(), nullable=True, comment='Repository base directory'))
    op.add_column('repositories', sa.Column('document_root_directory', sa.String(), nullable=True, comment="Document root directory (e.g., 'docs')"))
    op.add_column('repositories', sa.Column('root_document_path', sa.String(), nullable=True, comment="Main document file path (e.g., 'docs/README.md')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'root_document_path')
    op.drop_column('repositories', 'document_root_directory')
    op.drop_column('repositories', 'repository_root')
    # ### end Alembic commands ###
